apiVersion: v1
kind: Service
metadata:
  name: codemaster
  namespace: default
spec:
  type: NodePort
  selector:
    app: codemaster
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30004
      protocol: TCP
---
# Optional: NodePort for direct access (useful for testing)
# Uncomment if you don't have an Ingress controller
#
# apiVersion: v1
# kind: Service
# metadata:
#   name: codemaster-nodeport
#   namespace: codemaster
# spec:
#   type: NodePort
#   selector:
#     app: codemaster
#   ports:
#     - name: http
#       port: 80
#       targetPort: 80
#       nodePort: 30080
